name: Build Jekyll site and deploy

on:
 push:
   branches:
    - main
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            bibtex:
              - 'assets/bibtex/**/*'

      - name: Build the publication list (if bibtex entry was added or changed)
        if: steps.filter.outputs.bibtex == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

          pip install -U bibtexparser Jinja2 pyyaml

          cat assets/bibtex/*.bib > assets/bibtex/all.bib
          python3 scripts/bibparser.py -i assets/bibtex/all.bib -o _data/publication.yml


      - name: Build the jekyll page
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev

          ##################
          # Install Jekyll #
          ##################

          export GEM_HOME="$HOME/gems"
          export PATH="$HOME/gems/bin:$PATH"

          gem install jekyll bundler

          #####################
          # Build the website #
          #####################

          bundle install
          bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '_site/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4